name: mx_core
description: 通用基底
version: 7.4.3+3
homepage: https://github.com/MagicalWater

environment:
  sdk: ^3.5.3
  flutter: '>=3.24.3'

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

  # 解析圖片
  image: ^4.2.0

  # 本地文件
  path_provider: ^2.1.4

  # 輕量級資料儲存
  shared_preferences: ^2.3.2

  # 時間/數字格式化
  intl: ^0.19.0

  # android 的返回按鈕攔截
  back_button_interceptor: 7.0.3

  # 列表組件
  flutter_easyrefresh: ^2.2.2

  decimal: ^3.0.2

  rational: ^2.2.3

  flutter_secure_storage: 9.2.2

  collection: ^1.18.0

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: "^2.4.13"
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspecf

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.water.mx_core
        pluginClass: MxCorePlugin
      ios:
        pluginClass: MxCorePlugin
      web:
        pluginClass: MxCoreWeb
        fileName: mx_core_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  #  assets:
  #    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
